### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by nuggetsnetwork** [sortedcord/udemyscraper#54]
**Describe the bug**
Unable to install udemyscraper via pip install

**To Reproduce**
ERROR: Cannot install udemyscraper==0.8.1 and udemyscraper==0.8.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    udemyscraper 0.8.2 depends on getopt2==0.0.3
    udemyscraper 0.8.1 depends on getopt2==0.0.3

**Desktop (please complete the following information):**
 - OS: MAC OS

**Comment by sortedcord** [comment]
It is probably because of two conflicting versions. Try uninstalling udemyscraper (version 0.8.1) 
```
pip uninstall udemyscraper
```

Then try cloning the source code and then installing that directly
```
git clone https://github.com/sortedcord/udemyscraper.git
cd udemyscraper
pip install -e .[dev]
```

**Comment by nuggetsnetwork** [comment]
> It is probably because of two conflicting versions. Try uninstalling udemyscraper (version 0.8.1)
> 
> ```
> pip uninstall udemyscraper
> ```
> 
> Then try cloning the source code and then installing that directly
> 
> ```
> git clone https://github.com/sortedcord/udemyscraper.git
> cd udemyscraper
> pip install -e .[dev]
> ```

Infact none have got installed. So I dont have any package installed. The first instance of running it just throws me this error.
Running pip uninstall udemyscraper gives me warning that its not installed.

I have cloned as suggested. and when running pip install -e .[dev] gives me error no matches found: .[dev]
Sorry I might be a novice in doing this.

**Comment by nuggetsnetwork** [comment]
I just went ahead and tried below instead of pip install -e .[dev]
I ran python setup.py and I am getting below errors for getopt2 which might indicate similar error we got while installing via pip install udemyscraper

Searching for getopt2==0.0.3
Reading https://pypi.org/simple/getopt2/
Couldn't find index page for 'getopt2' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for getopt2==0.0.3
error: Could not find suitable distribution for Requirement.parse('getopt2==0.0.3')

**Comment by sortedcord** [comment]
Well, I should have seen this coming... The `getopt2` library isn't actually used by udemyscraper anymore. I'll remove that from the dependencies. Then maybe you wouldn't get this error anymore...

**Comment by nuggetsnetwork** [comment]
Thank you that resolves the issue.
